# Generated by Django 3.1.7 on 2021-10-28 09:27

from django.db import migrations, models
import index_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_critical', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to=index_app.models.images_directory_path, verbose_name='Превью')),
                ('written_at', models.DateField(verbose_name='Манга выпущена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('redacted_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
                ('categories', models.ManyToManyField(blank=True, to='index_app.Category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Манга',
                'verbose_name_plural': 'Манга',
                'ordering': ['-created_at'],
            },
        ),
    ]
