# Generated by Django 3.1.7 on 2022-01-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0004_comment_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
