# Generated by Django 3.1.7 on 2021-10-28 22:06

from django.db import migrations
import user_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_auto_20211028_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', user_app.models.CustomUserManager()),
            ],
        ),
    ]
